version: "3.7"
services:
  app:
    container_name: sc-app
    # restart: always
    build: .
    # depends_on:
    #   - mongodb
    ports:
      - "8000:8000"
    networks:
      - btlp-network
    volumes:
      - .:/app
      - /home/mega/github/jamir-browser-client/dist/:/app/jamir-browser-client-dist
    environment:
      - NODE_ENV=development
      - TZ=Europe/Moscow
    working_dir: /app

networks:
  btlp-network:
    driver: bridge