version: "3.7"
services:
  mongodb:
    container_name: mongodb
    # restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - btlp-network
    volumes:
      - mongo-db-volume:/data/db
      - mongo-configdb-volume:/data/configdb
    environment:
      - TZ=Europe/Moscow

networks:
  btlp-network:
    driver: bridge

volumes:
  mongo-db-volume:
    driver: local
  mongo-configdb-volume:
    driver: local
